CREATE TABLE IF NOT EXISTS USER (
    USER_ID        INTEGER(8) UNIQUE NOT NULL AUTO_INCREMENT,
    USERNAME       VARCHAR(35) NOT NULL,
    USER_LNAME     VARCHAR(35) NOT NULL,
    USER_FNAME     VARCHAR(35) NOT NULL,
    USER_EMAIL     VARCHAR(35) UNIQUE NOT NULL,
    USER_PASS_HASH VARCHAR(100) NOT NULL,
    VER_TOKEN      VARCHAR(100) DEFAULT NULL,
    VER_CODE       INTEGER(6) DEFAULT NULL,
    VERIFIED       BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS RESET_PASSWORD_TOKENS (
    USER_ID        INTEGER(8) NOT NULL,
    TOKEN        VARCHAR(50) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FILES (
    FILE_ID        INTEGER(8) UNIQUE NOT NULL AUTO_INCREMENT,
    FILENAME       VARCHAR(35) NOT NULL,
    FILESIZE       INTEGER(255) NOT NULL,
    FILEDATA       BLOB NOT NULL,
    TIME_SUBMITTED DATETIME DEFAULT NULL,
    USER_ID        INTEGER(8) NOT NULL,
    PRIMARY KEY (FILE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS APPOINTMENTS (
    APP_ID        INTEGER(8) UNIQUE NOT NULL AUTO_INCREMENT,
    TITLE         VARCHAR(35) NOT NULL,
    DESCRIPTION   VARCHAR(35) NOT NULL,
    APP_DATE      DATE NOT NULL,
    APP_TIME      TIME DEFAULT NULL,
    USER_ID       INTEGER(8) NOT NULL,
    PRIMARY KEY (APP_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON UPDATE CASCADE ON DELETE CASCADE
);
