CREATE DATABASE IF NOT EXISTS BRAND_CENTRAL;
ALTER DATABASE BRAND_CENTRAL CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
USE BRAND_CENTRAL;

SOURCE schema.sql;
SOURCE seed_db_products.sql;

CREATE DATABASE IF NOT EXISTS BRAND_CENTRAL_TESTING;
ALTER DATABASE BRAND_CENTRAL CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
USE BRAND_CENTRAL_TESTING;

SOURCE schema.sql;
SOURCE seed_db_products.sql;

/* Create database for session storage. */
CREATE DATABASE IF NOT EXISTS SESSION_STORE;
