CREATE DATABASE IF NOT EXISTS DROPBOX;
ALTER DATABASE DROPBOX CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
USE DROPBOX;

SOURCE schema.sql;

CREATE DATABASE IF NOT EXISTS DROPBOX_TESTING;
ALTER DATABASE DROPBOX CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
USE DROPBOX_TESTING;

SOURCE schema.sql;

/* Create database for session storage. */
CREATE DATABASE IF NOT EXISTS SESSION_STORE;
